//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://24sevenOffice.com/webservices", ConfigurationName="CompanyService.CompanyServiceSoap")]
    public interface CompanyServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/DeleteRelations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.Relation[]> DeleteRelationsAsync(CompanyService.Relation[] relations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/DeleteCompanies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.Company[]> DeleteCompaniesAsync(CompanyService.Company[] companies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/SaveRelations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.Relation[]> SaveRelationsAsync(CompanyService.Relation[] relations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/DeleteMaps", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.CompanyMap[]> DeleteMapsAsync(CompanyService.CompanyMap[] maps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/SaveMaps", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.CompanyMap[]> SaveMapsAsync(CompanyService.CompanyMap[] maps);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetCompanies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.Company[]> GetCompaniesAsync(CompanyService.CompanySearchParameters searchParams, string[] returnProperties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetCustomerCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int[]> GetCustomerCategoriesAsync(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetIndustries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.GetIndustriesResponse> GetIndustriesAsync(CompanyService.GetIndustriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/SaveCustomerCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.SaveCustomerCategoriesResponse> SaveCustomerCategoriesAsync(CompanyService.SaveCustomerCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/DeleteCustomerCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.DeleteCustomerCategoriesResponse> DeleteCustomerCategoriesAsync(CompanyService.DeleteCustomerCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetCustomerCategoryTree", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.GetCustomerCategoryTreeResponse> GetCustomerCategoryTreeAsync(CompanyService.GetCustomerCategoryTreeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/SaveCompanies", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.Company[]> SaveCompaniesAsync(CompanyService.Company[] companies);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetStatuses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<CompanyService.GetStatusesResponse> GetStatusesAsync(CompanyService.GetStatusesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Relation
    {
        
        private int contactIdField;
        
        private int companyIdField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string roleField;
        
        private int roleIdField;
        
        private PhoneNumbers phoneNumbersField;
        
        private EmailAddresses emailAddressesField;
        
        private string faxField;
        
        public Relation()
        {
            this.contactIdField = -2147483648;
            this.companyIdField = -2147483648;
            this.firstNameField = "";
            this.lastNameField = "";
            this.roleField = "";
            this.roleIdField = -2147483648;
            this.faxField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ContactId
        {
            get
            {
                return this.contactIdField;
            }
            set
            {
                this.contactIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int RoleId
        {
            get
            {
                return this.roleIdField;
            }
            set
            {
                this.roleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public PhoneNumbers PhoneNumbers
        {
            get
            {
                return this.phoneNumbersField;
            }
            set
            {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public EmailAddresses EmailAddresses
        {
            get
            {
                return this.emailAddressesField;
            }
            set
            {
                this.emailAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class PhoneNumbers
    {
        
        private PhoneNumber homeField;
        
        private PhoneNumber faxField;
        
        private PhoneNumber mobileField;
        
        private PhoneNumber primaryField;
        
        private PhoneNumber workField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PhoneNumber Home
        {
            get
            {
                return this.homeField;
            }
            set
            {
                this.homeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PhoneNumber Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PhoneNumber Mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PhoneNumber Primary
        {
            get
            {
                return this.primaryField;
            }
            set
            {
                this.primaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public PhoneNumber Work
        {
            get
            {
                return this.workField;
            }
            set
            {
                this.workField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class PhoneNumber
    {
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class KeyValuePair
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Category
    {
        
        private int idField;
        
        private string nameField;
        
        private bool showContactField;
        
        private bool showCompanyField;
        
        public Category()
        {
            this.idField = -2147483648;
            this.nameField = "";
            this.showContactField = false;
            this.showCompanyField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowContact
        {
            get
            {
                return this.showContactField;
            }
            set
            {
                this.showContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ShowCompany
        {
            get
            {
                return this.showCompanyField;
            }
            set
            {
                this.showCompanyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class CompanySearchParameters
    {
        
        private string externalIdField;
        
        private int companyIdField;
        
        private string companyNameField;
        
        private System.DateTime changedAfterField;
        
        private string companyEmailField;
        
        private string companyPhoneField;
        
        public CompanySearchParameters()
        {
            this.companyIdField = -2147483648;
            this.companyNameField = "";
            this.changedAfterField = new System.DateTime(0);
            this.companyEmailField = "";
            this.companyPhoneField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExternalId
        {
            get
            {
                return this.externalIdField;
            }
            set
            {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime ChangedAfter
        {
            get
            {
                return this.changedAfterField;
            }
            set
            {
                this.changedAfterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CompanyEmail
        {
            get
            {
                return this.companyEmailField;
            }
            set
            {
                this.companyEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string CompanyPhone
        {
            get
            {
                return this.companyPhoneField;
            }
            set
            {
                this.companyPhoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class CompanyMap
    {
        
        private int mapTypeField;
        
        private string externalIdField;
        
        private int companyIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MapType
        {
            get
            {
                return this.mapTypeField;
            }
            set
            {
                this.mapTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExternalId
        {
            get
            {
                return this.externalIdField;
            }
            set
            {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Address
    {
        
        private string streetField;
        
        private string stateField;
        
        private string postalCodeField;
        
        private string postalAreaField;
        
        private string nameField;
        
        private string cityField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PostalArea
        {
            get
            {
                return this.postalAreaField;
            }
            set
            {
                this.postalAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Addresses
    {
        
        private Address postField;
        
        private Address deliveryField;
        
        private Address visitField;
        
        private Address invoiceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Address Post
        {
            get
            {
                return this.postField;
            }
            set
            {
                this.postField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address Delivery
        {
            get
            {
                return this.deliveryField;
            }
            set
            {
                this.deliveryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Address Visit
        {
            get
            {
                return this.visitField;
            }
            set
            {
                this.visitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Address Invoice
        {
            get
            {
                return this.invoiceField;
            }
            set
            {
                this.invoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class APIException
    {
        
        private string typeField;
        
        private string messageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Company
    {
        
        private APIException aPIExceptionField;
        
        private int idField;
        
        private string externalIdField;
        
        private string organizationNumberField;
        
        private string nameField;
        
        private string firstNameField;
        
        private string nickNameField;
        
        private Addresses addressesField;
        
        private PhoneNumbers phoneNumbersField;
        
        private EmailAddresses emailAddressesField;
        
        private string urlField;
        
        private string countryField;
        
        private string noteField;
        
        private string invoiceLanguageField;
        
        private CompanyType typeField;
        
        private string usernameField;
        
        private string passwordField;
        
        private System.DateTime incorporationDateField;
        
        private System.DateTime dateCreatedField;
        
        private int statusField;
        
        private int priceListField;
        
        private int ownerField;
        
        private string bankAccountNoField;
        
        private int termsOfDeliveryIdField;
        
        private short accountDebitField;
        
        private short accountCreditField;
        
        private decimal discountField;
        
        private int typeGroupField;
        
        private decimal shareCapitalField;
        
        private int numberOfEmployeesField;
        
        private decimal turnoverField;
        
        private decimal profitField;
        
        private int industryIdField;
        
        private int memberNoField;
        
        private System.DateTime dateChangedField;
        
        private bool blockInvoiceField;
        
        private Relation[] relationsField;
        
        private CompanyMap[] mapsField;
        
        private DistributionMethod distributionMethodField;
        
        private CurrencyType currencyIdField;
        
        private short paymentTimeField;
        
        private string glnNumberField;
        
        private System.Nullable<bool> factoringField;
        
        private bool factoringFieldSpecified;
        
        private short ledgerCustomerAccountField;
        
        private short ledgerSupplierAccountField;
        
        private string vatNumberField;
        
        private System.Nullable<bool> privateField;
        
        private bool privateFieldSpecified;
        
        public Company()
        {
            this.idField = -2147483648;
            this.externalIdField = "";
            this.organizationNumberField = "";
            this.nameField = "";
            this.firstNameField = "";
            this.nickNameField = "";
            this.urlField = "";
            this.countryField = "EN";
            this.noteField = "";
            this.invoiceLanguageField = "";
            this.typeField = CompanyType.None;
            this.usernameField = "";
            this.passwordField = "";
            this.incorporationDateField = new System.DateTime(0);
            this.dateCreatedField = new System.DateTime(0);
            this.statusField = -2147483648;
            this.priceListField = -2147483648;
            this.ownerField = -2147483648;
            this.bankAccountNoField = "";
            this.termsOfDeliveryIdField = -2147483648;
            this.accountDebitField = ((short)(0));
            this.accountCreditField = ((short)(0));
            this.discountField = ((decimal)(0.0m));
            this.typeGroupField = -2147483648;
            this.shareCapitalField = ((decimal)(-79228162514264337593543950335m));
            this.numberOfEmployeesField = -2147483648;
            this.turnoverField = ((decimal)(-79228162514264337593543950335m));
            this.profitField = ((decimal)(-79228162514264337593543950335m));
            this.industryIdField = -2147483648;
            this.memberNoField = -2147483648;
            this.dateChangedField = new System.DateTime(0);
            this.blockInvoiceField = false;
            this.distributionMethodField = DistributionMethod.Unchanged;
            this.currencyIdField = CurrencyType.LOCAL;
            this.paymentTimeField = ((short)(-32768));
            this.glnNumberField = "";
            this.ledgerCustomerAccountField = ((short)(-32768));
            this.ledgerSupplierAccountField = ((short)(-32768));
            this.vatNumberField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public APIException APIException
        {
            get
            {
                return this.aPIExceptionField;
            }
            set
            {
                this.aPIExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ExternalId
        {
            get
            {
                return this.externalIdField;
            }
            set
            {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string OrganizationNumber
        {
            get
            {
                return this.organizationNumberField;
            }
            set
            {
                this.organizationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string NickName
        {
            get
            {
                return this.nickNameField;
            }
            set
            {
                this.nickNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Addresses Addresses
        {
            get
            {
                return this.addressesField;
            }
            set
            {
                this.addressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public PhoneNumbers PhoneNumbers
        {
            get
            {
                return this.phoneNumbersField;
            }
            set
            {
                this.phoneNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public EmailAddresses EmailAddresses
        {
            get
            {
                return this.emailAddressesField;
            }
            set
            {
                this.emailAddressesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DefaultValueAttribute("EN")]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string InvoiceLanguage
        {
            get
            {
                return this.invoiceLanguageField;
            }
            set
            {
                this.invoiceLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DefaultValueAttribute(CompanyType.None)]
        public CompanyType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime IncorporationDate
        {
            get
            {
                return this.incorporationDateField;
            }
            set
            {
                this.incorporationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int PriceList
        {
            get
            {
                return this.priceListField;
            }
            set
            {
                this.priceListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Owner
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string BankAccountNo
        {
            get
            {
                return this.bankAccountNoField;
            }
            set
            {
                this.bankAccountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TermsOfDeliveryId
        {
            get
            {
                return this.termsOfDeliveryIdField;
            }
            set
            {
                this.termsOfDeliveryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "0")]
        public short AccountDebit
        {
            get
            {
                return this.accountDebitField;
            }
            set
            {
                this.accountDebitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "0")]
        public short AccountCredit
        {
            get
            {
                return this.accountCreditField;
            }
            set
            {
                this.accountCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal Discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int TypeGroup
        {
            get
            {
                return this.typeGroupField;
            }
            set
            {
                this.typeGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal ShareCapital
        {
            get
            {
                return this.shareCapitalField;
            }
            set
            {
                this.shareCapitalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int NumberOfEmployees
        {
            get
            {
                return this.numberOfEmployeesField;
            }
            set
            {
                this.numberOfEmployeesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Turnover
        {
            get
            {
                return this.turnoverField;
            }
            set
            {
                this.turnoverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Profit
        {
            get
            {
                return this.profitField;
            }
            set
            {
                this.profitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int IndustryId
        {
            get
            {
                return this.industryIdField;
            }
            set
            {
                this.industryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int MemberNo
        {
            get
            {
                return this.memberNoField;
            }
            set
            {
                this.memberNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged
        {
            get
            {
                return this.dateChangedField;
            }
            set
            {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool BlockInvoice
        {
            get
            {
                return this.blockInvoiceField;
            }
            set
            {
                this.blockInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=36)]
        public Relation[] Relations
        {
            get
            {
                return this.relationsField;
            }
            set
            {
                this.relationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=37)]
        public CompanyMap[] Maps
        {
            get
            {
                return this.mapsField;
            }
            set
            {
                this.mapsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        [System.ComponentModel.DefaultValueAttribute(DistributionMethod.Unchanged)]
        public DistributionMethod DistributionMethod
        {
            get
            {
                return this.distributionMethodField;
            }
            set
            {
                this.distributionMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        [System.ComponentModel.DefaultValueAttribute(CurrencyType.LOCAL)]
        public CurrencyType CurrencyId
        {
            get
            {
                return this.currencyIdField;
            }
            set
            {
                this.currencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short PaymentTime
        {
            get
            {
                return this.paymentTimeField;
            }
            set
            {
                this.paymentTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string GlnNumber
        {
            get
            {
                return this.glnNumberField;
            }
            set
            {
                this.glnNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public System.Nullable<bool> Factoring
        {
            get
            {
                return this.factoringField;
            }
            set
            {
                this.factoringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FactoringSpecified
        {
            get
            {
                return this.factoringFieldSpecified;
            }
            set
            {
                this.factoringFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short LedgerCustomerAccount
        {
            get
            {
                return this.ledgerCustomerAccountField;
            }
            set
            {
                this.ledgerCustomerAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        [System.ComponentModel.DefaultValueAttribute(typeof(short), "-32768")]
        public short LedgerSupplierAccount
        {
            get
            {
                return this.ledgerSupplierAccountField;
            }
            set
            {
                this.ledgerSupplierAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string VatNumber
        {
            get
            {
                return this.vatNumberField;
            }
            set
            {
                this.vatNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public System.Nullable<bool> Private
        {
            get
            {
                return this.privateField;
            }
            set
            {
                this.privateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrivateSpecified
        {
            get
            {
                return this.privateFieldSpecified;
            }
            set
            {
                this.privateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class EmailAddresses
    {
        
        private EmailAddress homeField;
        
        private EmailAddress invoiceField;
        
        private EmailAddress primaryField;
        
        private EmailAddress workField;
        
        private EmailAddress alternativeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EmailAddress Home
        {
            get
            {
                return this.homeField;
            }
            set
            {
                this.homeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EmailAddress Invoice
        {
            get
            {
                return this.invoiceField;
            }
            set
            {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public EmailAddress Primary
        {
            get
            {
                return this.primaryField;
            }
            set
            {
                this.primaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public EmailAddress Work
        {
            get
            {
                return this.workField;
            }
            set
            {
                this.workField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public EmailAddress Alternative
        {
            get
            {
                return this.alternativeField;
            }
            set
            {
                this.alternativeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class EmailAddress
    {
        
        private string descriptionField;
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum CompanyType
    {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Lead,
        
        /// <remarks/>
        Consumer,
        
        /// <remarks/>
        Business,
        
        /// <remarks/>
        Supplier,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum DistributionMethod
    {
        
        /// <remarks/>
        Unchanged,
        
        /// <remarks/>
        Print,
        
        /// <remarks/>
        EMail,
        
        /// <remarks/>
        ElectronicInvoice,
        
        /// <remarks/>
        Default,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public enum CurrencyType
    {
        
        /// <remarks/>
        LOCAL,
        
        /// <remarks/>
        AED,
        
        /// <remarks/>
        AFN,
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        AMD,
        
        /// <remarks/>
        ANG,
        
        /// <remarks/>
        AOA,
        
        /// <remarks/>
        ARS,
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        AWG,
        
        /// <remarks/>
        AZN,
        
        /// <remarks/>
        BAM,
        
        /// <remarks/>
        BBD,
        
        /// <remarks/>
        BDT,
        
        /// <remarks/>
        BGN,
        
        /// <remarks/>
        BHD,
        
        /// <remarks/>
        BIF,
        
        /// <remarks/>
        BMD,
        
        /// <remarks/>
        BND,
        
        /// <remarks/>
        BOB,
        
        /// <remarks/>
        BOV,
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        BSD,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BWP,
        
        /// <remarks/>
        BYN,
        
        /// <remarks/>
        BYR,
        
        /// <remarks/>
        BZD,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        CDF,
        
        /// <remarks/>
        CHE,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        CHW,
        
        /// <remarks/>
        CLF,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        CNY,
        
        /// <remarks/>
        COP,
        
        /// <remarks/>
        COU,
        
        /// <remarks/>
        CRC,
        
        /// <remarks/>
        CUC,
        
        /// <remarks/>
        CUP,
        
        /// <remarks/>
        CVE,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DJF,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        DOP,
        
        /// <remarks/>
        DZD,
        
        /// <remarks/>
        EEK,
        
        /// <remarks/>
        EGP,
        
        /// <remarks/>
        ERN,
        
        /// <remarks/>
        ETB,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        FJD,
        
        /// <remarks/>
        FKP,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        GEL,
        
        /// <remarks/>
        GHS,
        
        /// <remarks/>
        GIP,
        
        /// <remarks/>
        GMD,
        
        /// <remarks/>
        GNF,
        
        /// <remarks/>
        GTQ,
        
        /// <remarks/>
        GYD,
        
        /// <remarks/>
        HKD,
        
        /// <remarks/>
        HNL,
        
        /// <remarks/>
        HRK,
        
        /// <remarks/>
        HTG,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        IDR,
        
        /// <remarks/>
        ILS,
        
        /// <remarks/>
        INR,
        
        /// <remarks/>
        IQD,
        
        /// <remarks/>
        IRR,
        
        /// <remarks/>
        ISK,
        
        /// <remarks/>
        JMD,
        
        /// <remarks/>
        JOD,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        KES,
        
        /// <remarks/>
        KGS,
        
        /// <remarks/>
        KHR,
        
        /// <remarks/>
        KMF,
        
        /// <remarks/>
        KPW,
        
        /// <remarks/>
        KRW,
        
        /// <remarks/>
        KWD,
        
        /// <remarks/>
        KYD,
        
        /// <remarks/>
        KZT,
        
        /// <remarks/>
        LAK,
        
        /// <remarks/>
        LBP,
        
        /// <remarks/>
        LKR,
        
        /// <remarks/>
        LRD,
        
        /// <remarks/>
        LSL,
        
        /// <remarks/>
        LTL,
        
        /// <remarks/>
        LVL,
        
        /// <remarks/>
        LYD,
        
        /// <remarks/>
        MAD,
        
        /// <remarks/>
        MDL,
        
        /// <remarks/>
        MGA,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MMK,
        
        /// <remarks/>
        MNT,
        
        /// <remarks/>
        MOP,
        
        /// <remarks/>
        MRO,
        
        /// <remarks/>
        MTL,
        
        /// <remarks/>
        MUR,
        
        /// <remarks/>
        MVR,
        
        /// <remarks/>
        MWK,
        
        /// <remarks/>
        MXN,
        
        /// <remarks/>
        MXV,
        
        /// <remarks/>
        MYR,
        
        /// <remarks/>
        MZN,
        
        /// <remarks/>
        NAD,
        
        /// <remarks/>
        NGN,
        
        /// <remarks/>
        NIO,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        NPR,
        
        /// <remarks/>
        NZD,
        
        /// <remarks/>
        OMR,
        
        /// <remarks/>
        PAB,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        PGK,
        
        /// <remarks/>
        PHP,
        
        /// <remarks/>
        PKR,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        PYG,
        
        /// <remarks/>
        QAR,
        
        /// <remarks/>
        RON,
        
        /// <remarks/>
        RSD,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        RWF,
        
        /// <remarks/>
        SAR,
        
        /// <remarks/>
        SBD,
        
        /// <remarks/>
        SCR,
        
        /// <remarks/>
        SDG,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        SGD,
        
        /// <remarks/>
        SHP,
        
        /// <remarks/>
        SKK,
        
        /// <remarks/>
        SLL,
        
        /// <remarks/>
        SOS,
        
        /// <remarks/>
        SRD,
        
        /// <remarks/>
        STD,
        
        /// <remarks/>
        SYP,
        
        /// <remarks/>
        SZL,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        TJS,
        
        /// <remarks/>
        TMT,
        
        /// <remarks/>
        TND,
        
        /// <remarks/>
        TOP,
        
        /// <remarks/>
        TRY,
        
        /// <remarks/>
        TTD,
        
        /// <remarks/>
        TWD,
        
        /// <remarks/>
        TZS,
        
        /// <remarks/>
        UAH,
        
        /// <remarks/>
        UGX,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        UYU,
        
        /// <remarks/>
        UZS,
        
        /// <remarks/>
        VEF,
        
        /// <remarks/>
        VND,
        
        /// <remarks/>
        VUV,
        
        /// <remarks/>
        WST,
        
        /// <remarks/>
        XAF,
        
        /// <remarks/>
        XAG,
        
        /// <remarks/>
        XAU,
        
        /// <remarks/>
        XBA,
        
        /// <remarks/>
        XBB,
        
        /// <remarks/>
        XBC,
        
        /// <remarks/>
        XBD,
        
        /// <remarks/>
        XCD,
        
        /// <remarks/>
        XDR,
        
        /// <remarks/>
        XFU,
        
        /// <remarks/>
        XOF,
        
        /// <remarks/>
        XPD,
        
        /// <remarks/>
        XPF,
        
        /// <remarks/>
        XPT,
        
        /// <remarks/>
        XTS,
        
        /// <remarks/>
        XXX,
        
        /// <remarks/>
        YER,
        
        /// <remarks/>
        ZAR,
        
        /// <remarks/>
        ZMK,
        
        /// <remarks/>
        ZWL,
        
        /// <remarks/>
        ZWD,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIndustries", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class GetIndustriesRequest
    {
        
        public GetIndustriesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetIndustriesResponse", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class GetIndustriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CompanyService.KeyValuePair[] GetIndustriesResult;
        
        public GetIndustriesResponse()
        {
        }
        
        public GetIndustriesResponse(CompanyService.KeyValuePair[] GetIndustriesResult)
        {
            this.GetIndustriesResult = GetIndustriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveCustomerCategories", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class SaveCustomerCategoriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CompanyService.KeyValuePair[] customerCategories;
        
        public SaveCustomerCategoriesRequest()
        {
        }
        
        public SaveCustomerCategoriesRequest(CompanyService.KeyValuePair[] customerCategories)
        {
            this.customerCategories = customerCategories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveCustomerCategoriesResponse", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class SaveCustomerCategoriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        public CompanyService.APIException[] SaveCustomerCategoriesResult;
        
        public SaveCustomerCategoriesResponse()
        {
        }
        
        public SaveCustomerCategoriesResponse(CompanyService.APIException[] SaveCustomerCategoriesResult)
        {
            this.SaveCustomerCategoriesResult = SaveCustomerCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCustomerCategories", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class DeleteCustomerCategoriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CompanyService.KeyValuePair[] customerCategories;
        
        public DeleteCustomerCategoriesRequest()
        {
        }
        
        public DeleteCustomerCategoriesRequest(CompanyService.KeyValuePair[] customerCategories)
        {
            this.customerCategories = customerCategories;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteCustomerCategoriesResponse", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class DeleteCustomerCategoriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        public CompanyService.APIException[] DeleteCustomerCategoriesResult;
        
        public DeleteCustomerCategoriesResponse()
        {
        }
        
        public DeleteCustomerCategoriesResponse(CompanyService.APIException[] DeleteCustomerCategoriesResult)
        {
            this.DeleteCustomerCategoriesResult = DeleteCustomerCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerCategoryTree", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class GetCustomerCategoryTreeRequest
    {
        
        public GetCustomerCategoryTreeRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCustomerCategoryTreeResponse", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class GetCustomerCategoryTreeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CompanyService.KeyValuePair[] GetCustomerCategoryTreeResult;
        
        public GetCustomerCategoryTreeResponse()
        {
        }
        
        public GetCustomerCategoryTreeResponse(CompanyService.KeyValuePair[] GetCustomerCategoryTreeResult)
        {
            this.GetCustomerCategoryTreeResult = GetCustomerCategoryTreeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatuses", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class GetStatusesRequest
    {
        
        public GetStatusesRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusesResponse", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class GetStatusesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public CompanyService.KeyValuePair[] GetStatusesResult;
        
        public GetStatusesResponse()
        {
        }
        
        public GetStatusesResponse(CompanyService.KeyValuePair[] GetStatusesResult)
        {
            this.GetStatusesResult = GetStatusesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface CompanyServiceSoapChannel : CompanyService.CompanyServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class CompanyServiceSoapClient : System.ServiceModel.ClientBase<CompanyService.CompanyServiceSoap>, CompanyService.CompanyServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CompanyServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CompanyServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), CompanyServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompanyServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CompanyServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompanyServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CompanyServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CompanyServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<CompanyService.Relation[]> DeleteRelationsAsync(CompanyService.Relation[] relations)
        {
            return base.Channel.DeleteRelationsAsync(relations);
        }
        
        public System.Threading.Tasks.Task<CompanyService.Company[]> DeleteCompaniesAsync(CompanyService.Company[] companies)
        {
            return base.Channel.DeleteCompaniesAsync(companies);
        }
        
        public System.Threading.Tasks.Task<CompanyService.Relation[]> SaveRelationsAsync(CompanyService.Relation[] relations)
        {
            return base.Channel.SaveRelationsAsync(relations);
        }
        
        public System.Threading.Tasks.Task<CompanyService.CompanyMap[]> DeleteMapsAsync(CompanyService.CompanyMap[] maps)
        {
            return base.Channel.DeleteMapsAsync(maps);
        }
        
        public System.Threading.Tasks.Task<CompanyService.CompanyMap[]> SaveMapsAsync(CompanyService.CompanyMap[] maps)
        {
            return base.Channel.SaveMapsAsync(maps);
        }
        
        public System.Threading.Tasks.Task<CompanyService.Company[]> GetCompaniesAsync(CompanyService.CompanySearchParameters searchParams, string[] returnProperties)
        {
            return base.Channel.GetCompaniesAsync(searchParams, returnProperties);
        }
        
        public System.Threading.Tasks.Task<CompanyService.Category[]> GetCategoriesAsync()
        {
            return base.Channel.GetCategoriesAsync();
        }
        
        public System.Threading.Tasks.Task<int[]> GetCustomerCategoriesAsync(int customerId)
        {
            return base.Channel.GetCustomerCategoriesAsync(customerId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyService.GetIndustriesResponse> CompanyService.CompanyServiceSoap.GetIndustriesAsync(CompanyService.GetIndustriesRequest request)
        {
            return base.Channel.GetIndustriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyService.GetIndustriesResponse> GetIndustriesAsync()
        {
            CompanyService.GetIndustriesRequest inValue = new CompanyService.GetIndustriesRequest();
            return ((CompanyService.CompanyServiceSoap)(this)).GetIndustriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyService.SaveCustomerCategoriesResponse> CompanyService.CompanyServiceSoap.SaveCustomerCategoriesAsync(CompanyService.SaveCustomerCategoriesRequest request)
        {
            return base.Channel.SaveCustomerCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyService.SaveCustomerCategoriesResponse> SaveCustomerCategoriesAsync(CompanyService.KeyValuePair[] customerCategories)
        {
            CompanyService.SaveCustomerCategoriesRequest inValue = new CompanyService.SaveCustomerCategoriesRequest();
            inValue.customerCategories = customerCategories;
            return ((CompanyService.CompanyServiceSoap)(this)).SaveCustomerCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyService.DeleteCustomerCategoriesResponse> CompanyService.CompanyServiceSoap.DeleteCustomerCategoriesAsync(CompanyService.DeleteCustomerCategoriesRequest request)
        {
            return base.Channel.DeleteCustomerCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyService.DeleteCustomerCategoriesResponse> DeleteCustomerCategoriesAsync(CompanyService.KeyValuePair[] customerCategories)
        {
            CompanyService.DeleteCustomerCategoriesRequest inValue = new CompanyService.DeleteCustomerCategoriesRequest();
            inValue.customerCategories = customerCategories;
            return ((CompanyService.CompanyServiceSoap)(this)).DeleteCustomerCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyService.GetCustomerCategoryTreeResponse> CompanyService.CompanyServiceSoap.GetCustomerCategoryTreeAsync(CompanyService.GetCustomerCategoryTreeRequest request)
        {
            return base.Channel.GetCustomerCategoryTreeAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyService.GetCustomerCategoryTreeResponse> GetCustomerCategoryTreeAsync()
        {
            CompanyService.GetCustomerCategoryTreeRequest inValue = new CompanyService.GetCustomerCategoryTreeRequest();
            return ((CompanyService.CompanyServiceSoap)(this)).GetCustomerCategoryTreeAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<CompanyService.Company[]> SaveCompaniesAsync(CompanyService.Company[] companies)
        {
            return base.Channel.SaveCompaniesAsync(companies);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CompanyService.GetStatusesResponse> CompanyService.CompanyServiceSoap.GetStatusesAsync(CompanyService.GetStatusesRequest request)
        {
            return base.Channel.GetStatusesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CompanyService.GetStatusesResponse> GetStatusesAsync()
        {
            CompanyService.GetStatusesRequest inValue = new CompanyService.GetStatusesRequest();
            return ((CompanyService.CompanyServiceSoap)(this)).GetStatusesAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CompanyServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CompanyServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CompanyServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.24sevenoffice.com/CRM/Company/V001/CompanyService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CompanyServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.24sevenoffice.com/CRM/Company/V001/CompanyService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CompanyServiceSoap,
            
            CompanyServiceSoap12,
        }
    }
}
