//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://24sevenOffice.com/webservices", ConfigurationName="ProductService.ProductServiceSoap")]
    public interface ProductServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/SetStockQuantity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> SetStockQuantityAsync(int productId, decimal stockQuantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.Product[]> GetProductsAsync(ProductService.ProductSearchParameters searchParams, string[] returnProperties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/SaveProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.Product[]> SaveProductsAsync(ProductService.Product[] products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/DeleteProducts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.Product[]> DeleteProductsAsync(ProductService.Product[] products);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetPriceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.GetPriceListResponse> GetPriceListAsync(ProductService.GetPriceListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetAllPriceLists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.ProductPriceList[]> GetAllPriceListsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.Category[]> GetCategoriesAsync(string[] returnProperties);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/SaveCategories", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.Category[]> SaveCategoriesAsync(ProductService.Category[] categories);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetDiscountMatrixPriceGroup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.Discount[]> GetDiscountMatrixPriceGroupAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://24sevenOffice.com/webservices/GetDiscountMatrixCategory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ProductService.Discount[]> GetDiscountMatrixCategoryAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProductSearchParameters
    {
        
        private int idField;
        
        private int categoryIdField;
        
        private string noField;
        
        private string eAN1Field;
        
        private string nameField;
        
        private decimal priceField;
        
        private System.DateTime dateChangedField;
        
        private int[] productIdsField;
        
        public ProductSearchParameters()
        {
            this.idField = -2147483648;
            this.categoryIdField = -2147483648;
            this.noField = "";
            this.eAN1Field = "";
            this.nameField = "";
            this.priceField = ((decimal)(-79228162514264337593543950335m));
            this.dateChangedField = new System.DateTime(0);
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string EAN1
        {
            get
            {
                return this.eAN1Field;
            }
            set
            {
                this.eAN1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged
        {
            get
            {
                return this.dateChangedField;
            }
            set
            {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public int[] ProductIds
        {
            get
            {
                return this.productIdsField;
            }
            set
            {
                this.productIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Discount
    {
        
        private int priceGroupIdField;
        
        private int categoryIdField;
        
        private int customerIdField;
        
        private decimal valueField;
        
        public Discount()
        {
            this.priceGroupIdField = -2147483648;
            this.categoryIdField = -2147483648;
            this.customerIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int PriceGroupId
        {
            get
            {
                return this.priceGroupIdField;
            }
            set
            {
                this.priceGroupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Category
    {
        
        private int idField;
        
        private string nameField;
        
        private string noField;
        
        private int parentIdField;
        
        private APIException aPIExceptionField;
        
        public Category()
        {
            this.idField = -2147483648;
            this.nameField = "";
            this.noField = "";
            this.parentIdField = -2147483648;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int ParentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public APIException APIException
        {
            get
            {
                return this.aPIExceptionField;
            }
            set
            {
                this.aPIExceptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class APIException
    {
        
        private string typeField;
        
        private string messageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class ProductPriceList
    {
        
        private int idField;
        
        private string nameField;
        
        private bool incVatField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IncVat
        {
            get
            {
                return this.incVatField;
            }
            set
            {
                this.incVatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class KeyValuePair
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://24sevenOffice.com/webservices")]
    public partial class Product
    {
        
        private double cashPriceIncTaxField;
        
        private decimal webPriceField;
        
        private int supplierIdField;
        
        private int idField;
        
        private string nameField;
        
        private decimal taxRateField;
        
        private decimal stockField;
        
        private int statusIdField;
        
        private int categoryIdField;
        
        private int priceGroupIDField;
        
        private decimal inPriceField;
        
        private string descriptionField;
        
        private string descriptionLongField;
        
        private decimal costField;
        
        private string eAN1Field;
        
        private decimal priceField;
        
        private string noField;
        
        private System.DateTime dateChangedField;
        
        private APIException aPIExceptionField;
        
        private decimal weightField;
        
        private decimal minimumStockField;
        
        private decimal orderProposalField;
        
        private string stockLocationField;
        
        private string supplierProductCodeField;
        
        private string supplierProductNameField;
        
        private System.Nullable<bool> webField;
        
        private bool webFieldSpecified;
        
        private string productCodeField;
        
        private System.Nullable<bool> stockControlledField;
        
        private bool stockControlledFieldSpecified;
        
        private System.Nullable<bool> newOfferField;
        
        private bool newOfferFieldSpecified;
        
        private System.Nullable<bool> newProductField;
        
        private bool newProductFieldSpecified;
        
        public Product()
        {
            this.cashPriceIncTaxField = -1.7976931348623157E+308D;
            this.webPriceField = ((decimal)(-79228162514264337593543950335m));
            this.supplierIdField = -2147483648;
            this.idField = -2147483648;
            this.nameField = "";
            this.taxRateField = ((decimal)(-79228162514264337593543950335m));
            this.stockField = ((decimal)(-79228162514264337593543950335m));
            this.statusIdField = -2147483648;
            this.categoryIdField = -2147483648;
            this.priceGroupIDField = -2147483648;
            this.inPriceField = ((decimal)(-79228162514264337593543950335m));
            this.descriptionField = "";
            this.descriptionLongField = "";
            this.costField = ((decimal)(-79228162514264337593543950335m));
            this.eAN1Field = "";
            this.priceField = ((decimal)(-79228162514264337593543950335m));
            this.noField = "";
            this.dateChangedField = new System.DateTime(0);
            this.weightField = ((decimal)(-79228162514264337593543950335m));
            this.minimumStockField = ((decimal)(-79228162514264337593543950335m));
            this.orderProposalField = ((decimal)(-79228162514264337593543950335m));
            this.stockLocationField = "";
            this.supplierProductCodeField = "";
            this.supplierProductNameField = "";
            this.productCodeField = "";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DefaultValueAttribute(-1.7976931348623157E+308D)]
        public double CashPriceIncTax
        {
            get
            {
                return this.cashPriceIncTaxField;
            }
            set
            {
                this.cashPriceIncTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal WebPrice
        {
            get
            {
                return this.webPriceField;
            }
            set
            {
                this.webPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int SupplierId
        {
            get
            {
                return this.supplierIdField;
            }
            set
            {
                this.supplierIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal TaxRate
        {
            get
            {
                return this.taxRateField;
            }
            set
            {
                this.taxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Stock
        {
            get
            {
                return this.stockField;
            }
            set
            {
                this.stockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int StatusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DefaultValueAttribute(-2147483648)]
        public int PriceGroupID
        {
            get
            {
                return this.priceGroupIDField;
            }
            set
            {
                this.priceGroupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal InPrice
        {
            get
            {
                return this.inPriceField;
            }
            set
            {
                this.inPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string DescriptionLong
        {
            get
            {
                return this.descriptionLongField;
            }
            set
            {
                this.descriptionLongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Cost
        {
            get
            {
                return this.costField;
            }
            set
            {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string EAN1
        {
            get
            {
                return this.eAN1Field;
            }
            set
            {
                this.eAN1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        [System.ComponentModel.DefaultValueAttribute(typeof(System.DateTime), "0001-01-01T00:00:00")]
        public System.DateTime DateChanged
        {
            get
            {
                return this.dateChangedField;
            }
            set
            {
                this.dateChangedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public APIException APIException
        {
            get
            {
                return this.aPIExceptionField;
            }
            set
            {
                this.aPIExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal MinimumStock
        {
            get
            {
                return this.minimumStockField;
            }
            set
            {
                this.minimumStockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "-79228162514264337593543950335")]
        public decimal OrderProposal
        {
            get
            {
                return this.orderProposalField;
            }
            set
            {
                this.orderProposalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string StockLocation
        {
            get
            {
                return this.stockLocationField;
            }
            set
            {
                this.stockLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string SupplierProductCode
        {
            get
            {
                return this.supplierProductCodeField;
            }
            set
            {
                this.supplierProductCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string SupplierProductName
        {
            get
            {
                return this.supplierProductNameField;
            }
            set
            {
                this.supplierProductNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public System.Nullable<bool> Web
        {
            get
            {
                return this.webField;
            }
            set
            {
                this.webField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WebSpecified
        {
            get
            {
                return this.webFieldSpecified;
            }
            set
            {
                this.webFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        [System.ComponentModel.DefaultValueAttribute("")]
        public string ProductCode
        {
            get
            {
                return this.productCodeField;
            }
            set
            {
                this.productCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public System.Nullable<bool> StockControlled
        {
            get
            {
                return this.stockControlledField;
            }
            set
            {
                this.stockControlledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StockControlledSpecified
        {
            get
            {
                return this.stockControlledFieldSpecified;
            }
            set
            {
                this.stockControlledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<bool> NewOffer
        {
            get
            {
                return this.newOfferField;
            }
            set
            {
                this.newOfferField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewOfferSpecified
        {
            get
            {
                return this.newOfferFieldSpecified;
            }
            set
            {
                this.newOfferFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<bool> NewProduct
        {
            get
            {
                return this.newProductField;
            }
            set
            {
                this.newProductField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewProductSpecified
        {
            get
            {
                return this.newProductFieldSpecified;
            }
            set
            {
                this.newProductFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPriceList", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class GetPriceListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        public int priceListId;
        
        public GetPriceListRequest()
        {
        }
        
        public GetPriceListRequest(int priceListId)
        {
            this.priceListId = priceListId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPriceListResponse", WrapperNamespace="http://24sevenOffice.com/webservices", IsWrapped=true)]
    public partial class GetPriceListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://24sevenOffice.com/webservices", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ProductService.KeyValuePair[] GetPriceListResult;
        
        public GetPriceListResponse()
        {
        }
        
        public GetPriceListResponse(ProductService.KeyValuePair[] GetPriceListResult)
        {
            this.GetPriceListResult = GetPriceListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface ProductServiceSoapChannel : ProductService.ProductServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class ProductServiceSoapClient : System.ServiceModel.ClientBase<ProductService.ProductServiceSoap>, ProductService.ProductServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ProductServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> SetStockQuantityAsync(int productId, decimal stockQuantity)
        {
            return base.Channel.SetStockQuantityAsync(productId, stockQuantity);
        }
        
        public System.Threading.Tasks.Task<ProductService.Product[]> GetProductsAsync(ProductService.ProductSearchParameters searchParams, string[] returnProperties)
        {
            return base.Channel.GetProductsAsync(searchParams, returnProperties);
        }
        
        public System.Threading.Tasks.Task<ProductService.Product[]> SaveProductsAsync(ProductService.Product[] products)
        {
            return base.Channel.SaveProductsAsync(products);
        }
        
        public System.Threading.Tasks.Task<ProductService.Product[]> DeleteProductsAsync(ProductService.Product[] products)
        {
            return base.Channel.DeleteProductsAsync(products);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProductService.GetPriceListResponse> ProductService.ProductServiceSoap.GetPriceListAsync(ProductService.GetPriceListRequest request)
        {
            return base.Channel.GetPriceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProductService.GetPriceListResponse> GetPriceListAsync(int priceListId)
        {
            ProductService.GetPriceListRequest inValue = new ProductService.GetPriceListRequest();
            inValue.priceListId = priceListId;
            return ((ProductService.ProductServiceSoap)(this)).GetPriceListAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ProductService.ProductPriceList[]> GetAllPriceListsAsync()
        {
            return base.Channel.GetAllPriceListsAsync();
        }
        
        public System.Threading.Tasks.Task<ProductService.Category[]> GetCategoriesAsync(string[] returnProperties)
        {
            return base.Channel.GetCategoriesAsync(returnProperties);
        }
        
        public System.Threading.Tasks.Task<ProductService.Category[]> SaveCategoriesAsync(ProductService.Category[] categories)
        {
            return base.Channel.SaveCategoriesAsync(categories);
        }
        
        public System.Threading.Tasks.Task<ProductService.Discount[]> GetDiscountMatrixPriceGroupAsync()
        {
            return base.Channel.GetDiscountMatrixPriceGroupAsync();
        }
        
        public System.Threading.Tasks.Task<ProductService.Discount[]> GetDiscountMatrixCategoryAsync()
        {
            return base.Channel.GetDiscountMatrixCategoryAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ProductServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.24sevenoffice.com/Logistics/Product/V001/ProductService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ProductServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://api.24sevenoffice.com/Logistics/Product/V001/ProductService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ProductServiceSoap,
            
            ProductServiceSoap12,
        }
    }
}
